# Generated by Django 5.1.4 on 2025-06-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='dni',
        ),
        migrations.AddField(
            model_name='customuser',
            name='nombre',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
