# Generated by Django 6.0.4 on 2026-05-31 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Teléfono inválido. Use solo números, espacios, +, - o paréntesis (6-20 caracteres).', regex='^[\\d\\s+\\-()]{6,20}$')]),
        ),
        migrations.AddConstraint(
            model_name='customer',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), models.Q(('email', ''), _negated=True)), fields=('email',), name='uniq_customer_email'),
        ),
        migrations.AddConstraint(
            model_name='saleline',
            constraint=models.UniqueConstraint(fields=('sale', 'item'), name='uniq_saleline_sale_item'),
        ),
    ]
