# Generated by Django 6.0 on 2026-06-23 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_alter_customer_phone_customer_uniq_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScaleReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Lectura de balanza',
                'verbose_name_plural': 'Lecturas de balanza',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ScaleDeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50, unique=True)),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='operaciones.scalereading')),
            ],
            options={
                'verbose_name': 'Estado de balanza',
                'verbose_name_plural': 'Estados de balanza',
                'ordering': ['device_id'],
            },
        ),
    ]
