# Generated by Django 6.0 on 2026-06-23 19:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_scalereading_scaledevicestate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=50)),
                ('operador', models.CharField(max_length=150)),
                ('turno', models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('noche', 'Noche')], max_length=20)),
                ('tipo_producto', models.CharField(choices=[('saco', 'Saco'), ('caja', 'Caja')], max_length=20)),
                ('cliente', models.CharField(max_length=150)),
                ('producto', models.CharField(max_length=150)),
                ('almacen', models.CharField(max_length=150)),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('peso_esperado_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('peso_real_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('peso_diferencia_kg', models.DecimalField(decimal_places=3, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weight_records', to=settings.AUTH_USER_MODEL)),
                ('scale_reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weight_records', to='operaciones.scalereading')),
            ],
            options={
                'verbose_name': 'Registro de pesaje',
                'verbose_name_plural': 'Registros de pesaje',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
